export { default as PreviewSearchLeftStyledWidget } from './PreviewSearchStyled'
export { default as ProductCard } from './ProductCard'
export { default as MarqeRecomendation } from './MarqueRecommendation'
export { default as GenericRecommendation } from './GenericRecommendation'
export { default as SearchResultsBasic } from './SearchResults'
